<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <UserSecretsId>5e6bdb96-66c8-42ea-ba48-27e96fd69970</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DirectoryService.Contracts\DirectoryService.Contracts.csproj"/>
        <ProjectReference Include="..\DirectoryService.Core\DirectoryService.Core.csproj"/>
        <ProjectReference Include="..\DirectoryService.Domain\DirectoryService.Domain.csproj"/>
        <ProjectReference Include="..\DirectoryService.Infrastructure.Postgres\DirectoryService.Infrastructure.Postgres.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Microsoft.OpenApi" />
        <PackageReference Include="Scalar.AspNetCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools"/>
    </ItemGroup>

</Project>
